In [ ]:
# Author: Hunter Darling, MTH-496 Quiz 2 - Logistic Regression

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
minmax_scaler = preprocessing.MinMaxScaler()
stand_scaler = preprocessing.StandardScaler()

In [2]:
df_train = pd.read_csv('data/noshow_train.csv')
df_test = pd.read_csv('data/noshow_test.csv')
# may need to change to omit features

In [20]:
df_train.head()

PatientId  AppointmentID Gender          ScheduledDay  \
0  1.328182e+08        5564358      F  2016-04-11T07:32:09Z   
1  6.414363e+12        5697382      M  2016-05-13T15:41:49Z   
2  8.499273e+12        5630770      F  2016-04-27T16:18:15Z   
3  5.258463e+10        5650746      F  2016-05-03T08:04:43Z   
4  6.234618e+14        5533700      F  2016-03-31T14:19:08Z   

         AppointmentDay  Age   Neighbourhood  Scholarship  Hipertension  \
0  2016-05-10T00:00:00Z   35     SANTA CLARA            0             0   
1  2016-05-20T00:00:00Z   50        DA PENHA            0             0   
2  2016-05-03T00:00:00Z    7      ANDORINHAS            0             0   
3  2016-05-10T00:00:00Z   16  NOVA PALESTINA            0             0   
4  2016-04-29T00:00:00Z   27    SANTA TEREZA            0             0   

   Diabetes  Alcoholism  Handcap  SMS_received  No-show  
0         0           0        0             1        0  
1         0           0        0             0        0  
2         0           0        0             0        1  
3         0           0        0             1        0  
4         0           0        0             1        1

In [4]:
df_test.head()

PatientId  AppointmentID Gender          ScheduledDay  \
0  8.523459e+13        5695263      M  2016-05-13T09:51:06Z   
1  1.783438e+12        5683970      M  2016-05-11T08:05:20Z   
2  1.445577e+10        5724179      F  2016-05-20T09:07:02Z   
3  6.245924e+13        5619919      M  2016-04-26T08:28:06Z   
4  8.996231e+13        5764117      F  2016-06-02T09:51:32Z   

         AppointmentDay  Age   Neighbourhood  Scholarship  Hipertension  \
0  2016-05-16T00:00:00Z   73         ITARARÉ            0             1   
1  2016-05-11T00:00:00Z    0    SÃO BENEDITO            0             0   
2  2016-05-20T00:00:00Z   21  GRANDE VITÓRIA            0             0   
3  2016-05-04T00:00:00Z   48      ANDORINHAS            0             0   
4  2016-06-03T00:00:00Z   15          BONFIM            0             0   

   Diabetes  Alcoholism  Handcap  SMS_received  
0         1           0        0             0  
1         0           0        0             0  
2         0           0        0             0  
3         0           0        0             1  
4         0           0        0             0

In [58]:
df_train_fixed = df_train.copy()
df_test_fixed = df_test.copy()
df_train_fixed['Gender_coded'] = df_train['Gender'].map({'M':1, 'F':0})
df_test_fixed['Gender_coded'] = df_test['Gender'].map({'M':1, 'F':0})
#bins = (0, 50, 120)
#group_names = ['young','old']
#df_train_fixed['Age'] = pd.cut(df_train_fixed['Age'], bins=bins, labels=group_names)
#df_test_fixed['Age'] = pd.cut(df_test_fixed['Age'], bins=bins, labels=group_names)
#df_train_fixed['Age_coded'] = df_train_fixed['Age'].map({'old':1, 'young':0})
#df_test_fixed['Age_coded'] = df_test_fixed['Age'].map({'old':1, 'young':0})

X_train = df_train_fixed.drop(['PatientId','AppointmentID','Gender','Age','ScheduledDay','AppointmentDay',
                         'Neighbourhood','No-show'],axis=1).values
y_train = df_train_fixed[['No-show']].values
X_test = df_test_fixed.drop(['PatientId','AppointmentID','Gender','Age','ScheduledDay','AppointmentDay','Neighbourhood'],axis=1).values
y_train.shape

(74053, 1)

In [59]:
X_train.shape

(74053, 7)

In [60]:
X_train[:10]

array([[0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [61]:
X_test.shape

(36474, 7)

In [62]:
y_train[:10]

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

### No Standardization

In [63]:
logreg = LogisticRegression(penalty='none', solver='saga', max_iter = 10000)
logreg.fit(X_train, y_train.ravel())
y_pred = logreg.predict(X_test)
y_pred[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Standardized with MinMaxScaler

In [64]:
minmax_scaler.fit(X_train) 
X_train_minmax = minmax_scaler.transform(X_train)
X_test_minmax = minmax_scaler.transform(X_test)
logreg2 = LogisticRegression(penalty = 'none', solver = 'saga', max_iter= 10000)
logreg2.fit(X_train_minmax, y_train.ravel())
y_pred_minmax = logreg2.predict(X_test_minmax)
y_pred_minmax[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
#X_train_minmax[:10]

### Standardized with StandardScaler

In [65]:
stand_scaler.fit(X_train)
X_train_stand = stand_scaler.transform(X_train)
X_test_stand = stand_scaler.transform(X_test)
logreg3 = LogisticRegression(penalty = 'none', solver = 'saga', max_iter= 10000)
logreg3.fit(X_train_stand, y_train.ravel())
y_pred_stand = logreg3.predict(X_test_stand)
y_pred_stand[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
#X_train_stand[:10]