In [2]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

<font color=red> Load Dataset </font>

In [3]:
df_train = pd.read_csv('data/noshow_train.csv')
df_test = pd.read_csv('data/noshow_test.csv')

In [7]:
df_train.head()

PatientId  AppointmentID Gender          ScheduledDay  \
0  1.328182e+08        5564358      F  2016-04-11T07:32:09Z   
1  6.414363e+12        5697382      M  2016-05-13T15:41:49Z   
2  8.499273e+12        5630770      F  2016-04-27T16:18:15Z   
3  5.258463e+10        5650746      F  2016-05-03T08:04:43Z   
4  6.234618e+14        5533700      F  2016-03-31T14:19:08Z   

         AppointmentDay  Age   Neighbourhood  Scholarship  Hipertension  \
0  2016-05-10T00:00:00Z   35     SANTA CLARA            0             0   
1  2016-05-20T00:00:00Z   50        DA PENHA            0             0   
2  2016-05-03T00:00:00Z    7      ANDORINHAS            0             0   
3  2016-05-10T00:00:00Z   16  NOVA PALESTINA            0             0   
4  2016-04-29T00:00:00Z   27    SANTA TEREZA            0             0   

   Diabetes  Alcoholism  Handcap  SMS_received  No-show  
0         0           0        0             1        0  
1         0           0        0             0        0  
2         0           0        0             0        1  
3         0           0        0             1        0  
4         0           0        0             1        1

<font color=red> Missing values </font>

In [4]:
#check missing values for the training data
df_train.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [5]:
#check missing values for the test data
df_test.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
dtype: int64

<font color=red> Handle non-number features </font>

In [6]:
#check to see which features are non-number
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74053 entries, 0 to 74052
Data columns (total 14 columns):
PatientId         74053 non-null float64
AppointmentID     74053 non-null int64
Gender            74053 non-null object
ScheduledDay      74053 non-null object
AppointmentDay    74053 non-null object
Age               74053 non-null int64
Neighbourhood     74053 non-null object
Scholarship       74053 non-null int64
Hipertension      74053 non-null int64
Diabetes          74053 non-null int64
Alcoholism        74053 non-null int64
Handcap           74053 non-null int64
SMS_received      74053 non-null int64
No-show           74053 non-null int64
dtypes: float64(1), int64(9), object(4)
memory usage: 7.9+ MB


In [8]:
# drop non-number features
feature_drops = []
df_train_fixed = df_train.drop(['Gender','ScheduledDay','AppointmentDay','Neighbourhood'], axis=1)
df_test_fixed = df_test.drop(['Gender','ScheduledDay','AppointmentDay','Neighbourhood'], axis=1)

<font color=red> Extract features from training </font>

In [17]:
X_train = df_train_fixed.drop('No-show', axis=1).values

In [18]:
X_train

array([[1.32818181e+08, 5.56435800e+06, 3.50000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [6.41436332e+12, 5.69738200e+06, 5.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.49927345e+12, 5.63077000e+06, 7.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.43936672e+09, 5.70865700e+06, 3.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.92386687e+12, 5.69565200e+06, 2.70000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.87764570e+13, 5.69011600e+06, 1.10000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

<font color=red> Collect the training labels </font>

In [19]:
y_train = df_train['No-show'].values

In [20]:
y_train

array([0, 0, 1, ..., 0, 0, 1])

<font color=red> Extract test features </font>

In [21]:
X_test = df_test_fixed.values

In [22]:
X_test

array([[8.52345869e+13, 5.69526300e+06, 7.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.78343782e+12, 5.68397000e+06, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.44557672e+10, 5.72417900e+06, 2.10000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [5.93118818e+12, 5.64491200e+06, 7.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.42278576e+14, 5.72014300e+06, 7.10000000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.58626654e+12, 5.69223700e+06, 1.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

Scale features

In [23]:
from sklearn import preprocessing as pp
std_scaler = pp.StandardScaler()
std_scaler.fit(X_train)
X_train_std_sk = std_scaler.transform(X_train)
X_test_std_sk = std_scaler.transform(X_test)

Initialize and train model

In [24]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(penalty='none', 
                            solver='saga', 
                            multi_class='ovr')
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='none',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

<font color=red> Predict test labels</font>

In [25]:
y_pred = logreg.predict(X_test_std_sk)

<font color=red>Get real labels</font>

In [26]:
y_real = pd.read_csv('data/noshow_test_labels.csv').values

<font color=red> Confusion matrix </font>

[[predict label 0 correctly, predict label 0 incorrectly],<br>
  [predict label 1 incorrectly, predict label 1 correctly]]
  
  = [[TN, FP],
    [FN, TP]]

<font color=red> Accuracy </font>

<font color=red> True/False Positive/Negative and ROC curve </font>

sklearn.metrics.roc_curve(y_true, y_score, pos_label=None, sample_weight=None, drop_intermediate=True)

return fpr, tpr, thresholds

<font color=red>Get y_score</font>

<font color=red> ROC curve</font>

<font color=red>Draw ROC curve</font>

<font color=red> AUC score </font>

<font color=red> Precision-Recall Curve </font>

<font color=red> Draw P-R curve </font>

<font color=red> Calculate Average-Precision Score </font>

<font color=red> F1 score </font>